CXX := mpiicpc

HEFFTE_ROOT ?= $(HOME)/local/heffte-oneapi-mkl

CXXFLAGS := -std=c++17 -O3 -march=core-avx2 -Wall -Wextra -pedantic \
            -diag-disable=11074,11076 \
            -DSHHD_HEFFTE_BACKEND_MKL \
            -Isrc \
            -I$(HEFFTE_ROOT)/include \
            -I$(MKLROOT)/include

LDFLAGS := -L$(HEFFTE_ROOT)/lib -L$(MKLROOT)/lib/intel64

LDLIBS := -lheffte \
          -lmkl_intel_lp64 -lmkl_sequential -lmkl_core \
          -lpthread -lm -ldl

TARGET := src/out.exe
SRCS := \
	src/main.cc \
	src/buffer_flux.cc \
	src/buffer_physical_state.cc \
	src/domain.cc \
	src/fcalculator.cc \
	src/fcalculator_workspace.cc \
	src/initial_condition.cc \
	src/initial_condition_registry_builtin.cc \
	src/initial_condition_gaussian_density.cc \
	src/initial_condition_gaussian_order_parameter.cc \
	src/initial_condition_random_vorticity_momentum.cc \
	src/initial_condition_sine_density.cc \
	src/initial_condition_sine_momentum.cc \
	src/initial_condition_sine_order_parameter.cc \
	src/initial_condition_uniform_density.cc \
	src/initial_condition_uniform_momentum.cc \
	src/initial_condition_uniform_order_parameter.cc \
	src/measure_registry_builtin.cc \
	src/measure_manager.cc \
	src/measure_energetics.cc \
	src/measure_snapshot.cc \
	src/model_free_energy_null.cc \
	src/model_free_energy_phi4.cc \
	src/model_free_energy_quadratic.cc \
	src/model_free_energy_registry_builtin.cc \
	src/model_thermodynamics_linear_eos.cc \
	src/model_thermodynamics_null.cc \
	src/model_thermodynamics_registry_builtin.cc \
	src/model_transport_coefficient_constant.cc \
	src/model_transport_coefficient_registry_builtin.cc \
	src/monitor.cc \
	src/param_parser.cc \
	src/spectral_mask.cc \
	src/state.cc \
	src/simulationinfo.cc

.PHONY: all clean

all: $(TARGET)

$(TARGET): $(SRCS)
	$(CXX) $(CXXFLAGS) $(SRCS) $(LDFLAGS) $(LDLIBS) -o $@

clean:
	rm -f $(TARGET)
