dimension           2
boundary            p p

grid                256 256
length              256.0 256.0
dealias             three_halves

order_parameters    0

timestep            0.01
time_evolution      srk3/incompressible

model transport     constant eta 0.1 zeta 0.0

fix                 1 momentum nonlinear on
fix                 2 momentum noise on seed 12345 kBT 1.0

set                 density uniform value 1.0
set                 momentum all equilibrium/gaussian/incompressible kBT 1.0 seed 67890

thermo              observe on progress on nevery 10000
restart             off

measure             ts time_series on nevery 1000 file examples/04_yokota_green_kubo/results/time_series_incompressible.dat target E_T E_K pi_xy
measure             gk yokota_green_kubo on nevery 10000 nblock 500000 file examples/04_yokota_green_kubo/results/yokota_green_kubo_incompressible.dat mode diagonal

run                 5000000
