#ifndef SHHD_MODEL_TRANSPORT_COEFFICIENT_REGISTRY_BUILTIN_H
#define SHHD_MODEL_TRANSPORT_COEFFICIENT_REGISTRY_BUILTIN_H

#include "model_transport_coefficient_registry.h"

TransportCoefficientRegistry build_transport_coefficient_registry();

#endif
