dimension           2
boundary            p p

grid                128 128
length              4096 4096
dealias             three_halves

order_parameters    1

timestep            4.0
time_evolution      srk3/incompressible

model free_energy   quadratic a[0] 1.0
model transport     constant eta 0.12 zeta 0.0 M[0,0] 0.12

fix                 1 order_parameter nonlinear on
fix                 2 momentum noise on seed 12345 kBT 1.0
fix                 3 order_parameter force/sine on component 0 axis y nk 1 amplitude 2.8237164691e-08

set                 density uniform value 1.0
set                 momentum all uniform value 0.0
set                 order_parameter all uniform value 0.0

thermo              observe on progress off nevery 100
restart             off

measure             1 time_series on nevery 250 file examples/05_order_parameter_kolmogorov_flow/raw_data/time_series.dat target E_T E_K E_psi |psi[0]|^2 |d_psi[0]|^2 Jpsi[0]_y
measure             2 ave/profile on axis y nevery 100 nblock 10000 file examples/05_order_parameter_kolmogorov_flow/raw_data/profile.dat average block target psi[0] Jpsi[0]_y vx pi_xy

run                 5000000
